# Data Scraping

## Latar Belakang
Pada tahap ini dilakukan proses pengumpulan data berupa ulasan pengguna aplikasi DANA yang diperoleh dari platform Google Play Store. Pengambilan data dilakukan secara mandiri menggunakan bahasa pemrograman Python dengan memanfaatkan library `google-play-scraper`, yang memungkinkan ekstraksi ulasan aplikasi secara langsung tanpa menggunakan API resmi.

In [1]:
# Instalasi library
!pip install google-play-scraper -q

In [2]:
from google_play_scraper import Sort, reviews
import pandas as pd

## Proses Scraping
Proses scraping dilakukan dengan mengambil 15.000 ulasan terbaru dari aplikasi DANA.

In [3]:
print("Sedang mengambil 15000 ulasan...")

result, continuation_token = reviews(
    'id.dana',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=15000
)

Sedang mengambil 15000 ulasan...

In [4]:
# Lihat hasil
df = pd.DataFrame(result)
print(f"\nTotal ulasan: {len(df)}")

Total ulasan: 15000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              15000 non-null  object
 1   userName              15000 non-null  object
 2   userImage             15000 non-null  object
 3   content               15000 non-null  object
 4   score                 15000 non-null  int64
 5   thumbsUpCount         15000 non-null  int64
 6   reviewCreatedVersion  12537 non-null  object
 7   at                    15000 non-null  datetime64[ns]
 8   replyContent          3459 non-null   object
 9   repliedAt             3459 non-null   datetime64[ns]
 10  appVersion            12537 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 1.3+ MB

In [6]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,d8621cfd-d005-4f9e-ab9b-e37273949401,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,good,5,0,2.120.1,2026-04-13 06:03:37,None,NaT,2.120.1
1,8a622047-40e1-42e8-8a61-a5da313bab5b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,dana sangat bagus,4,0,2.120.1,2026-04-13 05:58:01,None,NaT,2.120.1
2,c144ae14-09fb-4d53-bd4e-e9bd1310cea5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mantap sangat membantu financial,5,0,None,2026-04-13 05:57:26,None,NaT,None
3,262eb4a6-0f84-4c38-8f2a-4fabdae93c8d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat baik,5,0,None,2026-04-13 05:56:18,None,NaT,None
4,262c3d49-429b-4910-bbff-df3cbb87979a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,jozzz,4,0,2.120.1,2026-04-13 05:52:42,None,NaT,2.120.1

## Seleksi Fitur Data
Dari seluruh atribut yang diperoleh, hanya beberapa kolom yang relevan untuk analisis sentimen yang dipilih, yaitu:

*   `reviewId`: ID unik ulasan
*   `content`: isi teks ulasan
*   `score`: rating yang diberikan pengguna (1–5)

In [7]:
df_dana = df[['reviewId', 'content', 'score']]
df_dana.head()

,reviewId,content,score
0,d8621cfd-d005-4f9e-ab9b-e37273949401,good,5
1,8a622047-40e1-42e8-8a61-a5da313bab5b,dana sangat bagus,4
2,c144ae14-09fb-4d53-bd4e-e9bd1310cea5,mantap sangat membantu financial,5
3,262eb4a6-0f84-4c38-8f2a-4fabdae93c8d,sangat baik,5
4,262c3d49-429b-4910-bbff-df3cbb87979a,jozzz,4

## Simpan Dataset
Dataset hasil scraping kemudian disimpan dalam format `.csv` agar dapat digunakan pada tahap selanjutnya, seperti preprocessing dan pelatihan model.

In [8]:
df_dana.to_csv("dana_reviews.csv", index=False)